### ISSUE TITLE
Recommended way to deploy a production ready cluster

### ISSUE THREAD

**Issue by AlexGrs** [colemickens/azure-kubernetes-status#13]
Hi.

I can see in the description that one of the recommended deployment option is to use Azure Container Service. 

I tested it, it indeed deploy a full featured cluster but with only one master. So there cluster is, in my opinion, not really production ready. 

For you, what is the best solution today to deploy a production ready kubernetes on azure ? 

Rgds.

**Comment by colemickens** [comment]
Personally, I don't worry about HA for masters, since the cluster can safely coast under the master is back up.

That having been said, you're not the first person asking for HA. I've just created a tracking issue on ACS-Engine, which is where we would implement this before it would become available in the Azure Container Service: https://github.com/Azure/acs-engine/issues/129

**Comment by colemickens** [comment]
(Feel free to subscribe to that issue and close this one, unless you have further questions. Thanks!)

**Comment by colemickens** [comment]
Going to go ahead and close this. Feel free to reopen or file another issue if you have further questions. We'll track the status for HA on the Issue I created earlier: https://github.com/Azure/acs-engine/issues/129

**Comment by alexgrais** [comment]
Thank you !
